spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: CLOUD-SERVICE
server:
  port: 8087


eureka:
  instance:
    hostname: eureka-service-8761.com
    lease-renewal-interval-in-seconds: 1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service-8761.com:8761/eureka/
    registry-fetch-interval-seconds: 30 # 表示eureka client间隔多久去拉取服务注册信息