spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: EUREKA_SERVICE_1
server:
  port: 8761


eureka:
  instance:
    hostname: eureka-service-8761.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service-8761.com:8761/eureka/
