spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abcwangjingjing/configrepo.git
          username: abcwangjingjing
          password: ag528825
          basedir: F:\GitHubDemo\basedir  # 可以使用这个配置项来指定本地git仓库的路径
          search-paths: /**  # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开
server:
  port: 8070


eureka:
  instance:
    hostname: eureka-service-8761.com
    lease-renewal-interval-in-seconds: 1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service-8761.com:8761/eureka/
    registry-fetch-interval-seconds: 30 # 表示eureka client间隔多久去拉取服务注册信息



